name: typed
version: '0.8.1.0'
synopsis: Typed Lambda Calculus
description: Please see README.md
category: Other
author: myuon
maintainer: ioi.joi.koi.loi@gmail.com
copyright: 2016 myuon
license: MIT
github: myuon/typed

default-extensions:
- PatternSynonyms
- LambdaCase
- DataKinds
- TypeFamilies
- TypeApplications
- MultiParamTypeClasses
- FlexibleInstances
- TypeSynonymInstances
- OverloadedLabels

extra-source-files:
- README.md

dependencies:
- containers
- exceptions
- tasty-hunit

library:
  source-dirs: src
  dependencies:
  - base >=4.7 && <5
  - recursion-schemes

tests:
  typed:
    source-dirs: test
    main: Driver.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - typed
    - tasty
    - tasty-hunit
